# Generated by Django 6.0.3 on 2026-03-23 12:46

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='전화번호는 하이픈 없이 01012341234 형식이어야 합니다.', regex='^010[0-9]{8}$')])),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('profile_img_url', models.TextField(blank=True, null=True)),
                ('trust_score', models.DecimalField(decimal_places=1, default=Decimal('36.5'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))])),
                ('penalty_points', models.PositiveIntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_warning_active', models.BooleanField(default=False)),
                ('successful_streak_count', models.PositiveIntegerField(default=0)),
                ('last_score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='전화번호는 하이픈 없이 01012341234 형식이어야 합니다.', regex='^010[0-9]{8}$')])),
                ('blocked_until', models.DateTimeField()),
                ('trust_score_at_withdrawal', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))])),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('RELEASED', 'RELEASED')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('trust_score__gte', 0.0), ('trust_score__lte', 99.9)), name='accounts_user_trust_score_range'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('penalty_points__gte', 0)), name='accounts_user_penalty_points_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('successful_streak_count__gte', 0)), name='accounts_user_successful_streak_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F'])), name='accounts_user_gender_valid'),
        ),
        migrations.AddIndex(
            model_name='withdrawalblock',
            index=models.Index(fields=['phone_number', 'status'], name='accounts_wi_phone_n_1e2b68_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalblock',
            constraint=models.CheckConstraint(condition=models.Q(('trust_score_at_withdrawal__gte', 0.0), ('trust_score_at_withdrawal__lte', 99.9)), name='accounts_withdrawalblock_trust_score_range'),
        ),
    ]
