# Generated by Django 6.0.3 on 2026-03-16 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_trips_trip_capacity_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tripparticipant',
            name='seat_position',
            field=models.CharField(choices=[('FRONT_PASSENGER', 'FRONT_PASSENGER'), ('REAR_LEFT', 'REAR_LEFT'), ('REAR_RIGHT', 'REAR_RIGHT'), ('REAR_MIDDLE', 'REAR_MIDDLE')], default='FRONT_PASSENGER', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(fields=('trip', 'seat_position'), name='unique_trip_seat_position'),
        ),
    ]
