# Generated by Django 6.0.3 on 2026-03-23 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakaopay_link', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_channel', to='trips.trip')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_channels_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('total_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='trips.trip')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('memo_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('REQUEST', 'REQUEST'), ('PAID_SELF', 'PAID_SELF'), ('CONFIRMED', 'CONFIRMED'), ('DISPUTED', 'DISPUTED'), ('OVERDUE', 'OVERDUE'), ('CANCELED', 'CANCELED')], default='REQUEST', max_length=20)),
                ('verification_method', models.CharField(blank=True, choices=[('MANUAL', 'MANUAL'), ('PROOF_IMAGE', 'PROOF_IMAGE')], max_length=20, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_self_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('payee_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_to_receive', to=settings.AUTH_USER_MODEL)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_to_pay', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='trips.trip')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='settlements.receipt')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SettlementProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='settlements.settlement')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_proofs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='settlements_receipt_total_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(fields=('receipt', 'payer_user'), name='unique_receipt_payer_settlement'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('share_amount__gte', 0)), name='settlements_settlement_share_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('payer_user', models.F('payee_user')), _negated=True), name='settlements_payer_payee_must_differ'),
        ),
    ]
